feat(#188): Add Integration Test for Generics (failed)
objectionary/jeo-maven-plugin pull request #197
Opened 2023-10-25 14:57 UTC by volodya-lombrozo

Add integration test (failed) for checking correct transformation Java bytecode with Generics into EO and then back into Java.
The test should check that we don't break anything after transformation. Since we haven't implemented that feature yet, I've added 
one puzzle in order to enable this test in the future. 

Closes: #188.
____
History:
- feat(#188): Add simple integration test for generics
- feat(#188): Add new puzzle

2023-10-25 15:01 UTC, volodya-lombrozo commented
@levBagryansky Could you take a look, please?

2023-10-25 22:46 UTC, levBagryansky requested changes
@volodya-lombrozo Cool but some details are not clear for me

2023-10-25 22:46 UTC, levBagryansky commented on src/it/generics/src/main/java/org/eolang/jeo/Application.java
> +            new Language() {
@volodya-lombrozo Do we avoid annotations here?

2023-10-25 22:46 UTC, levBagryansky commented on src/it/generics/src/main/java/org/eolang/jeo/Application.java
> +        new Developer(
@volodya-lombrozo I'd like to see `new Developer<>` here to make it generic

2023-10-26 08:50 UTC, volodya-lombrozo commented
@levBagryansky Applied all your suggestions. Is it better now?

2023-10-26 09:54 UTC, levBagryansky approved these changes
@volodya-lombrozo yes, thanks!

2023-10-26 11:10 UTC, volodya-lombrozo commented
@rultor merge

2023-10-26 11:12 UTC, rultor commented
> @rultor merge

@volodya-lombrozo OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/35945-1780907616)

2023-10-26 11:15 UTC, merged

2023-10-26 11:16 UTC, rultor commented
> @rultor merge

@volodya-lombrozo Done! FYI, the full log is [here](https://www.rultor.com/t/35945-1780907616) (took me 3min)