feat(#650): qulice 0.23 java8 profile on jdk 1.8
objectionary/jeo-maven-plugin pull request #652
Opened 2024-08-01 10:40 UTC by h1alexbel

closes #650

2024-08-01 12:22 UTC, volodya-lombrozo requested changes

2024-08-01 12:22 UTC, volodya-lombrozo commented on pom.xml
> +        <jdk>1.8</jdk>
@h1alexbel By doing this, you automatically enable  `quliceJava8` or `qulice` plugins.  It means, if I run 
```shell
mvn clean install
```
I will run `quilice` as well. It's suboptimal during development process. More often we don't need to run `qulice` and check offences straight away. I personally run it only before creating a PR. 

So, I suggest to make `qulice` and `quliceJava8` included to `check` profile. [Here](https://stackoverflow.com/questions/943411/can-i-make-one-maven-profile-activate-another) is how you can achieve this.

2024-08-01 13:12 UTC, h1alexbel commented
@volodya-lombrozo updated, take a look, please

2024-08-01 15:32 UTC, volodya-lombrozo reviewed
@h1alexbel To be honest, I don't like the idea of changing the command we got use to:

```shell
mvn clean install -Pqulice --errors --batch-mode
```

I would like to preserve it. Is it possible to achieve?

2024-08-01 15:44 UTC, h1alexbel commented
@volodya-lombrozo Me as well. I think we should try to activate required version of qulice plugin itself based on Java version.

2024-08-01 15:58 UTC, h1alexbel commented
@volodya-lombrozo in order to preserve `-Pqulice` option, we can try to pass `-PquliceJava8` on java 8 builds. WDYT?

2024-08-02 08:33 UTC, volodya-lombrozo requested changes
@h1alexbel I have investigated the problem and found the way we can achieve the desired behaviour:
https://stackoverflow.com/a/78824495/10423604

Could you try it, please?

2024-08-02 08:40 UTC, h1alexbel commented
@volodya-lombrozo yes, I will try

2024-08-02 09:43 UTC, volodya-lombrozo approved these changes
@h1alexbel Looks good to me. Thank you.

2024-08-02 09:49 UTC, h1alexbel commented
@volodya-lombrozo thank you for suggestion approach with profile properties. Did not thought about them!

2024-08-02 09:49 UTC, volodya-lombrozo commented
@rultor merge

2024-08-02 09:51 UTC, rultor commented
> @rultor merge

@volodya-lombrozo OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/42909-2264999063)

2024-08-02 10:03 UTC, merged

2024-08-02 10:04 UTC, rultor commented
> @rultor merge

@volodya-lombrozo Done! FYI, the full log is [here](https://www.rultor.com/t/42909-2264999063) (took me 11min)

2024-08-02 12:29 UTC, 0crat commented
@h1alexbel Thanks for the contribution! You've earned +30 points. Please, [keep](https://www.yegor256.com/2018/03/06/speed-vs-quality.html) them coming. Your running balance is [+106](https://www.eolang.org/zerocracy/objectionary-vitals.html).

2024-08-02 12:29 UTC, 0crat commented
@volodya-lombrozo Thanks for the review! You've earned +27 points for this: +25 as a basis; +12 for the 126 hits-of-code that you reviewed; -10 for very few (1) comments.  Your running balance is [+279](https://www.eolang.org/zerocracy/objectionary-vitals.html).