feat(#824): Add `JNA` Integration Test
objectionary/jeo-maven-plugin pull request #825
Opened 2024-10-30 12:00 UTC by volodya-lombrozo

In this PR I successfully added an integration test that uses `JNA` library. This PR proves that 
`jeo-maven-plugin` works well with `JNA` classes.

Closes: #824.

2024-10-30 12:15 UTC, volodya-lombrozo commented
@yegor256 Could you take a look please? This test tries to resemble the issue you have here https://github.com/objectionary/hone-maven-plugin/issues/58
As you can see, everything works just fine. Please, correct me, if the test I wrote is different from what you have in `OptimizeMojoTest#optimizesJnaClasses`, in this case I will try to reproduce the same scenario.

As for the https://github.com/objectionary/hone-maven-plugin/issues/58 issue, it seems, that when you start testing `mvn test` the `JNA` library is just missing in the classpath.

2024-10-30 13:11 UTC, yegor256 commented
@volodya-lombrozo this way it works, but try to replace the `<dependency/>` in the `pom.xml` with this:

```
      <plugin>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>3.8.1</version>
        <executions>
          <execution>
            <phase>generate-resources</phase>
            <goals>
              <goal>unpack</goal>
            </goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>net.java.dev.jna</groupId>
                  <artifactId>jna</artifactId>
                  <version>5.15.0</version>
                  <type>jar</type>
                </artifactItem>
              </artifactItems>
              <outputDirectory>${project.build.outputDirectory}</outputDirectory>
            </configuration>
          </execution>
        </executions>
      </plugin>
```

Basically, you will unpack the dependency and let JEO process the `.class` files from JNA.

2024-10-30 13:32 UTC, yegor256 commented
@volodya-lombrozo use the latest version of EO: 0.40.3, it should be much faster

2024-10-30 13:39 UTC, volodya-lombrozo commented
@yegor256 It is with the `0.40.3` version already.

2024-10-31 10:16 UTC, volodya-lombrozo commented
@yegor256 Could you take a look one more time, please? I fixed the original problem in this PR: https://github.com/objectionary/jeo-maven-plugin/pull/827
Here I just prove that the solution solves the original problem with JNA classes. 

Pay attention, I excluded `phi/unphi` and `unroll` from the `jna` integration test because it takes too much time. Just to compare, the 'short' path (without `phi/unphi`) takes 13 seconds to run, while the `full` path takes 31 minutes. You can run the `full` path locally, to be sure, that everything works well. I've already done it myself:

```
[INFO] Building: jna/pom.xml
[INFO] run post-build script verify.groovy
[INFO]           jna/pom.xml ...................................... SUCCESS (1860 s)
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 1, Failed: 0, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  31:13 min
[INFO] Finished at: 2024-10-31T12:16:46+03:00
[INFO] ------------------------------------------------------------------------
```

2024-10-31 10:36 UTC, yegor256 requested changes
@volodya-lombrozo looks much better now, see one comment above

2024-10-31 10:36 UTC, yegor256 commented on src/it/jna/pom.xml
> +    <dependency>
@volodya-lombrozo you can remove it from the list of deps, since you unpack it

2024-10-31 11:14 UTC, volodya-lombrozo commented
@yegor256  Indeed! You are right, thank you. Removed this library. Could you have a look one more time, please?

Also I should warn you. If you remove `target/classes` folder somewhere, it might be a cause of serious issues. For example, `jna` library keeps native `.so` files inside `target/classes` and if you remove this folder entirely - it will crash your application.  By this reason, in my test I remove only `*.class` files from `target/classes` folder:

```xml
<plugin>
  <artifactId>maven-clean-plugin</artifactId>
  <version>3.4.0</version>
  <executions>
    <execution>
      <id>clean-target-classes</id>
      <phase>process-classes</phase>
      <goals>
        <goal>clean</goal>
      </goals>
      <configuration>
        <excludeDefaultDirectories>true</excludeDefaultDirectories>
        <filesets>
          <fileset>
            <directory>target/classes</directory>
            <includes>
              <include>**/*.class</include>
            </includes>
          </fileset>
        </filesets>
      </configuration>
    </execution>
  </executions>
</plugin>
```

2024-10-31 11:15 UTC, yegor256 approved these changes
@volodya-lombrozo LGTM

2024-10-31 11:31 UTC, rultor commented
> @rultor merge

@volodya-lombrozo OK, I'll try to merge now. You can check the progress of the merge [here](https://www.rultor.com/t/44890-2449611692).

2024-10-31 11:43 UTC, merged

2024-10-31 11:44 UTC, rultor commented
> @rultor merge

@volodya-lombrozo Done! FYI, the full log is [here](https://www.rultor.com/t/44890-2449611692) (took me 11min).